//! General-purpose embedded web asset and SPA responses for Axum.
//!
//! The asset provider owns the final identity, gzip, and Brotli bytes. This
//! crate negotiates those representations, exposes their SHA-256 values as
//! strong ETags, and applies a proxy-cache-safe HTTP contract without runtime
//! compression. By default ETags are formatted once during construction. The
//! `live-assets` feature instead resolves the file set and ETag metadata for
//! every request so a filesystem-backed debug provider can change in place.

#![forbid(unsafe_code)]

use std::{
    borrow::Cow,
    error::Error,
    fmt::{self, Write},
    marker::PhantomData,
};

#[cfg(not(feature = "live-assets"))]
use std::collections::HashMap;

use axum::{
    body::{Body, Bytes},
    extract::Request,
    http::{
        HeaderMap, HeaderValue, Method, StatusCode, Uri,
        header::{self, HeaderName},
    },
    response::Response,
};
use rust_embed::{EmbeddedFile, RustEmbed};

const X_CONTENT_TYPE_OPTIONS: HeaderName = HeaderName::from_static("x-content-type-options");
const DEFAULT_INDEX_CACHE_CONTROL: &str = "public, max-age=0, s-maxage=60, must-revalidate";
const DEFAULT_IMMUTABLE_CACHE_CONTROL: &str = "public, max-age=31536000, immutable";
const DEFAULT_REVALIDATE_CACHE_CONTROL: &str = "public, max-age=0, must-revalidate";
const DEFAULT_ERROR_CACHE_CONTROL: &str = "no-store";
const DEFAULT_CSP: &str = "default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; connect-src 'self' ws: wss:; base-uri 'none'; frame-ancestors 'none'; form-action 'self'";

/// Cache, fallback, and security-header policy for embedded web assets.
#[derive(Clone, Debug)]
pub struct EmbeddedSpaConfig {
    /// Logical path of the HTML entry point inside the embedded asset set.
    pub index_path: String,
    /// Path prefixes whose existing files are immutable and whose missing
    /// files must never fall back to the HTML entry point.
    pub immutable_prefixes: Vec<String>,
    /// Cache policy for the HTML entry point and SPA fallback responses.
    pub index_cache_control: String,
    /// Cache policy for files below an immutable prefix.
    pub immutable_cache_control: String,
    /// Cache policy for other existing embedded files.
    pub revalidate_cache_control: String,
    /// Cache policy for errors generated by this crate.
    pub error_cache_control: String,
    /// Optional Content Security Policy applied to the HTML entry point and
    /// status responses generated by this crate.
    pub content_security_policy: Option<String>,
}

impl Default for EmbeddedSpaConfig {
    fn default() -> Self {
        Self {
            index_path: "index.html".to_owned(),
            immutable_prefixes: vec!["assets/".to_owned()],
            index_cache_control: DEFAULT_INDEX_CACHE_CONTROL.to_owned(),
            immutable_cache_control: DEFAULT_IMMUTABLE_CACHE_CONTROL.to_owned(),
            revalidate_cache_control: DEFAULT_REVALIDATE_CACHE_CONTROL.to_owned(),
            error_cache_control: DEFAULT_ERROR_CACHE_CONTROL.to_owned(),
            content_security_policy: Some(DEFAULT_CSP.to_owned()),
        }
    }
}

impl EmbeddedSpaConfig {
    /// Override the cache policy used for the HTML entry point and SPA
    /// fallbacks.
    #[must_use]
    pub fn with_index_cache_control(mut self, value: impl Into<String>) -> Self {
        self.index_cache_control = value.into();
        self
    }

    /// Override or remove the Content Security Policy applied to the entry
    /// point and crate-generated status responses.
    #[must_use]
    pub fn with_content_security_policy(mut self, value: Option<impl Into<String>>) -> Self {
        self.content_security_policy = value.map(Into::into);
        self
    }
}

/// Configuration errors detected while constructing an [`EmbeddedSpa`].
#[derive(Debug)]
pub enum EmbeddedSpaError {
    /// The configured index path is not a safe relative asset path.
    InvalidIndexPath(String),
    /// The embedded provider does not contain the configured index.
    MissingIndex(String),
    /// A configured HTTP header cannot be represented by `HeaderValue`.
    InvalidHeader { name: &'static str, value: String },
}

impl fmt::Display for EmbeddedSpaError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidIndexPath(path) => {
                write!(formatter, "embedded SPA index path is invalid: {path:?}")
            }
            Self::MissingIndex(path) => {
                write!(formatter, "embedded SPA index is missing: {path}")
            }
            Self::InvalidHeader { name, value } => {
                write!(formatter, "invalid {name} header value: {value:?}")
            }
        }
    }
}

impl Error for EmbeddedSpaError {}

/// A reusable embedded web asset service backed by a [`RustEmbed`] provider.
pub struct EmbeddedSpa<A> {
    config: ValidatedConfig,
    #[cfg(not(feature = "live-assets"))]
    etags: HashMap<String, HeaderValue>,
    assets: PhantomData<fn() -> A>,
}

impl<A> EmbeddedSpa<A>
where
    A: RustEmbed,
{
    /// Validate configuration and prepare response ETag handling.
    ///
    /// The default build precomputes ETag header values. With the
    /// `live-assets` feature, ETags and the asset list are resolved from the
    /// provider at request time instead.
    pub fn new(config: EmbeddedSpaConfig) -> Result<Self, EmbeddedSpaError> {
        if !is_safe_relative_path(&config.index_path) {
            return Err(EmbeddedSpaError::InvalidIndexPath(config.index_path));
        }

        if A::get(&config.index_path).is_none() {
            return Err(EmbeddedSpaError::MissingIndex(config.index_path));
        }

        #[cfg(not(feature = "live-assets"))]
        let etags = A::iter()
            .filter_map(|path| {
                let file = A::get(path.as_ref())?;
                Some((path.into_owned(), strong_etag(file.metadata.sha256_hash())))
            })
            .collect();

        Ok(Self {
            config: ValidatedConfig::try_from(config)?,
            #[cfg(not(feature = "live-assets"))]
            etags,
            assets: PhantomData,
        })
    }

    /// Return the current number of files, including compressed siblings.
    #[must_use]
    pub fn asset_count(&self) -> usize {
        #[cfg(feature = "live-assets")]
        {
            A::iter().count()
        }

        #[cfg(not(feature = "live-assets"))]
        {
            self.etags.len()
        }
    }

    /// Convert an Axum request into a static, fallback, or error response.
    #[must_use]
    pub fn serve(&self, request: Request) -> Response {
        let (parts, _) = request.into_parts();

        if parts.method != Method::GET && parts.method != Method::HEAD {
            return self
                .status_response(StatusCode::METHOD_NOT_ALLOWED, Some(("allow", "GET, HEAD")));
        }

        let Some(requested_path) = safe_asset_path(&parts.uri, &self.config.index_path) else {
            return self.status_response(StatusCode::NOT_FOUND, None);
        };

        if requested_path.ends_with(".br") || requested_path.ends_with(".gz") {
            return self.status_response(StatusCode::NOT_FOUND, None);
        }

        if A::get(&requested_path).is_some() {
            return self.asset_response(&requested_path, &parts.method, &parts.headers, false);
        }

        if self.is_immutable_path(&requested_path) || !accepts_html(&parts.headers) {
            return self.status_response(StatusCode::NOT_FOUND, None);
        }

        self.asset_response(&self.config.index_path, &parts.method, &parts.headers, true)
    }

    fn asset_response(
        &self,
        logical_path: &str,
        method: &Method,
        request_headers: &HeaderMap,
        spa_fallback: bool,
    ) -> Response {
        let Some(selected) = select_representation::<A>(logical_path, request_headers) else {
            return self.status_response(StatusCode::NOT_ACCEPTABLE, None);
        };

        let Some(etag) = self.response_etag(&selected) else {
            return self.status_response(StatusCode::INTERNAL_SERVER_ERROR, None);
        };

        let cache_control = if logical_path == self.config.index_path || spa_fallback {
            &self.config.index_cache_control
        } else if self.is_immutable_path(logical_path) {
            &self.config.immutable_cache_control
        } else {
            &self.config.revalidate_cache_control
        };
        let not_modified = etag_matches(request_headers, &etag);
        let mut builder = Response::builder()
            .status(if not_modified {
                StatusCode::NOT_MODIFIED
            } else {
                StatusCode::OK
            })
            .header(header::ETAG, &etag)
            .header(header::CACHE_CONTROL, cache_control)
            .header(X_CONTENT_TYPE_OPTIONS, "nosniff");

        if selected.has_alternates {
            builder = builder.header(header::VARY, "Accept-Encoding");
        }

        if let Some(encoding) = selected.encoding {
            builder = builder.header(header::CONTENT_ENCODING, encoding);
        }

        if logical_path == self.config.index_path {
            if let Some(csp) = &self.config.content_security_policy {
                builder = builder.header(header::CONTENT_SECURITY_POLICY, csp);
            }
        }

        if not_modified {
            return builder
                .body(Body::empty())
                .expect("static 304 response is valid");
        }

        builder = builder
            .header(header::CONTENT_TYPE, content_type(logical_path))
            .header(header::CONTENT_LENGTH, selected.file.data.len());

        let body = if method == Method::HEAD {
            Body::empty()
        } else {
            match selected.file.data {
                Cow::Borrowed(bytes) => Body::from(Bytes::from_static(bytes)),
                Cow::Owned(bytes) => Body::from(bytes),
            }
        };

        builder.body(body).expect("static asset response is valid")
    }

    fn response_etag(&self, selected: &SelectedRepresentation) -> Option<HeaderValue> {
        #[cfg(feature = "live-assets")]
        {
            Some(strong_etag(selected.file.metadata.sha256_hash()))
        }

        #[cfg(not(feature = "live-assets"))]
        {
            self.etags.get(&selected.embedded_path).cloned()
        }
    }

    fn is_immutable_path(&self, path: &str) -> bool {
        self.config
            .immutable_prefixes
            .iter()
            .any(|prefix| path == prefix.trim_end_matches('/') || path.starts_with(prefix.as_str()))
    }

    fn status_response(
        &self,
        status: StatusCode,
        extra_header: Option<(&'static str, &'static str)>,
    ) -> Response {
        let mut builder = Response::builder()
            .status(status)
            .header(header::CACHE_CONTROL, &self.config.error_cache_control)
            .header(X_CONTENT_TYPE_OPTIONS, "nosniff");

        if let Some((name, value)) = extra_header {
            builder = builder.header(name, value);
        }

        if let Some(csp) = &self.config.content_security_policy {
            builder = builder.header(header::CONTENT_SECURITY_POLICY, csp);
        }

        builder
            .body(Body::empty())
            .expect("status response is valid")
    }
}

struct ValidatedConfig {
    index_path: String,
    immutable_prefixes: Vec<String>,
    index_cache_control: HeaderValue,
    immutable_cache_control: HeaderValue,
    revalidate_cache_control: HeaderValue,
    error_cache_control: HeaderValue,
    content_security_policy: Option<HeaderValue>,
}

impl TryFrom<EmbeddedSpaConfig> for ValidatedConfig {
    type Error = EmbeddedSpaError;

    fn try_from(config: EmbeddedSpaConfig) -> Result<Self, Self::Error> {
        Ok(Self {
            index_path: config.index_path,
            immutable_prefixes: config.immutable_prefixes,
            index_cache_control: header_value("Cache-Control", config.index_cache_control)?,
            immutable_cache_control: header_value("Cache-Control", config.immutable_cache_control)?,
            revalidate_cache_control: header_value(
                "Cache-Control",
                config.revalidate_cache_control,
            )?,
            error_cache_control: header_value("Cache-Control", config.error_cache_control)?,
            content_security_policy: config
                .content_security_policy
                .map(|value| header_value("Content-Security-Policy", value))
                .transpose()?,
        })
    }
}

fn header_value(name: &'static str, value: String) -> Result<HeaderValue, EmbeddedSpaError> {
    HeaderValue::from_str(&value).map_err(|_| EmbeddedSpaError::InvalidHeader { name, value })
}

struct SelectedRepresentation {
    #[cfg_attr(feature = "live-assets", allow(dead_code))]
    embedded_path: String,
    file: EmbeddedFile,
    encoding: Option<&'static str>,
    has_alternates: bool,
}

fn select_representation<A>(
    logical_path: &str,
    headers: &HeaderMap,
) -> Option<SelectedRepresentation>
where
    A: RustEmbed,
{
    let identity = A::get(logical_path)?;
    let br_path = format!("{logical_path}.br");
    let gzip_path = format!("{logical_path}.gz");
    let br = A::get(&br_path);
    let gzip = A::get(&gzip_path);
    let has_alternates = br.is_some() || gzip.is_some();
    let identity_quality = encoding_quality(headers, "identity");
    let mut selected = if identity_quality > 0 {
        Some((identity_quality, logical_path.to_owned(), identity, None))
    } else {
        None
    };

    if let Some(file) = gzip {
        let quality = encoding_quality(headers, "gzip");
        if quality > 0 && selected.as_ref().is_none_or(|current| quality >= current.0) {
            selected = Some((quality, gzip_path, file, Some("gzip")));
        }
    }

    if let Some(file) = br {
        let quality = encoding_quality(headers, "br");
        if quality > 0 && selected.as_ref().is_none_or(|current| quality >= current.0) {
            selected = Some((quality, br_path, file, Some("br")));
        }
    }

    selected.map(
        |(_, embedded_path, file, encoding)| SelectedRepresentation {
            embedded_path,
            file,
            encoding,
            has_alternates,
        },
    )
}

fn encoding_quality(headers: &HeaderMap, coding: &str) -> u16 {
    let mut wildcard = None;
    let mut exact = None;
    let mut saw_value = false;

    for header_value in headers.get_all(header::ACCEPT_ENCODING) {
        let Ok(header_value) = header_value.to_str() else {
            continue;
        };
        saw_value = true;

        for item in header_value.split(',') {
            let mut parts = item.trim().split(';');
            let name = parts.next().unwrap_or_default().trim();
            let quality = parts
                .find_map(|parameter| {
                    let (key, value) = parameter.trim().split_once('=')?;
                    key.eq_ignore_ascii_case("q")
                        .then(|| parse_quality(value.trim()).unwrap_or(0))
                })
                .unwrap_or(1000);

            if name.eq_ignore_ascii_case(coding) {
                exact = Some(quality);
            } else if name == "*" {
                wildcard = Some(quality);
            }
        }
    }

    if !saw_value {
        return u16::from(coding == "identity") * 1000;
    }

    exact.unwrap_or_else(|| wildcard.unwrap_or_else(|| u16::from(coding == "identity") * 1000))
}

fn parse_quality(value: &str) -> Option<u16> {
    let (whole, fraction) = value.split_once('.').map_or((value, ""), |parts| parts);
    if fraction.len() > 3 || !fraction.bytes().all(|byte| byte.is_ascii_digit()) {
        return None;
    }

    match whole {
        "1" if fraction.bytes().all(|byte| byte == b'0') => Some(1000),
        "0" => {
            let mut padded = fraction.to_owned();
            while padded.len() < 3 {
                padded.push('0');
            }
            padded.parse().ok()
        }
        _ => None,
    }
}

fn strong_etag(hash: [u8; 32]) -> HeaderValue {
    let mut value = String::with_capacity(73);
    value.push('"');
    value.push_str("sha256-");

    for byte in hash {
        write!(value, "{byte:02x}").expect("writing to a String cannot fail");
    }

    value.push('"');
    HeaderValue::from_str(&value).expect("SHA-256 ETag is a valid header value")
}

fn etag_matches(headers: &HeaderMap, current: &HeaderValue) -> bool {
    let Ok(current) = current.to_str() else {
        return false;
    };
    let current = current.strip_prefix("W/").unwrap_or(current);

    headers
        .get_all(header::IF_NONE_MATCH)
        .iter()
        .filter_map(|value| value.to_str().ok())
        .flat_map(|value| value.split(','))
        .any(|tag| {
            let tag = tag.trim();
            tag == "*" || tag.strip_prefix("W/").unwrap_or(tag) == current
        })
}

fn safe_asset_path(uri: &Uri, index_path: &str) -> Option<String> {
    let path = uri.path().trim_start_matches('/');

    if path.is_empty() {
        return Some(index_path.to_owned());
    }

    let path = path.trim_end_matches('/');

    is_safe_relative_path(path).then(|| path.to_owned())
}

fn is_safe_relative_path(path: &str) -> bool {
    !path.is_empty()
        && !path.starts_with('/')
        && !path.ends_with('/')
        && !path.contains("//")
        && !path.split('/').any(|segment| {
            segment.is_empty() || segment == "." || segment == ".." || segment.contains('\\')
        })
}

fn accepts_html(headers: &HeaderMap) -> bool {
    headers
        .get_all(header::ACCEPT)
        .iter()
        .filter_map(|value| value.to_str().ok())
        .flat_map(|value| value.split(','))
        .any(|item| {
            let mut parts = item.trim().split(';');
            let media_type = parts.next().unwrap_or_default().trim();
            let quality = parts
                .find_map(|parameter| {
                    let (key, value) = parameter.trim().split_once('=')?;
                    key.eq_ignore_ascii_case("q")
                        .then(|| parse_quality(value.trim()).unwrap_or(0))
                })
                .unwrap_or(1000);

            media_type.eq_ignore_ascii_case("text/html") && quality > 0
        })
}

fn content_type(path: &str) -> HeaderValue {
    if path.ends_with(".webmanifest") {
        return HeaderValue::from_static("application/manifest+json");
    }

    HeaderValue::from_str(mime_guess::from_path(path).first_or_octet_stream().as_ref())
        .expect("mime_guess only returns valid media types")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn absent_accept_encoding_prefers_identity() {
        let headers = HeaderMap::new();
        assert_eq!(encoding_quality(&headers, "identity"), 1000);
        assert_eq!(encoding_quality(&headers, "gzip"), 0);
        assert_eq!(encoding_quality(&headers, "br"), 0);
    }

    #[test]
    fn quality_values_and_wildcards_are_respected() {
        let mut headers = HeaderMap::new();
        headers.insert(
            header::ACCEPT_ENCODING,
            HeaderValue::from_static("gzip;q=0.6, br;q=1, *;q=0.2"),
        );
        assert_eq!(encoding_quality(&headers, "br"), 1000);
        assert_eq!(encoding_quality(&headers, "gzip"), 600);
        assert_eq!(encoding_quality(&headers, "zstd"), 200);

        headers.insert(header::ACCEPT_ENCODING, HeaderValue::from_static("*;q=0"));
        assert_eq!(encoding_quality(&headers, "identity"), 0);
    }

    #[test]
    fn repeated_accept_encoding_fields_are_combined() {
        let mut headers = HeaderMap::new();
        headers.append(
            header::ACCEPT_ENCODING,
            HeaderValue::from_static("gzip;q=0.4"),
        );
        headers.append(header::ACCEPT_ENCODING, HeaderValue::from_static("br;q=1"));

        assert_eq!(encoding_quality(&headers, "gzip"), 400);
        assert_eq!(encoding_quality(&headers, "br"), 1000);
    }

    #[test]
    fn quality_values_follow_the_http_grammar() {
        assert_eq!(parse_quality("0"), Some(0));
        assert_eq!(parse_quality("0.5"), Some(500));
        assert_eq!(parse_quality("0.123"), Some(123));
        assert_eq!(parse_quality("1.000"), Some(1000));
        assert_eq!(parse_quality("1.001"), None);
        assert_eq!(parse_quality("0.1234"), None);
        assert_eq!(parse_quality("-0.1"), None);
        assert_eq!(parse_quality("NaN"), None);
    }

    #[test]
    fn weak_if_none_match_can_validate_a_strong_etag_for_get() {
        let mut headers = HeaderMap::new();
        headers.append(
            header::IF_NONE_MATCH,
            HeaderValue::from_static("\"sha256-other\""),
        );
        headers.append(
            header::IF_NONE_MATCH,
            HeaderValue::from_static("W/\"sha256-example\""),
        );

        assert!(etag_matches(
            &headers,
            &HeaderValue::from_static("\"sha256-example\"")
        ));
    }

    #[test]
    fn unsafe_paths_are_rejected() {
        assert!(safe_asset_path(&"/../secret".parse().unwrap(), "index.html").is_none());
        assert!(safe_asset_path(&"/assets//app.js".parse().unwrap(), "index.html").is_none());
        assert_eq!(
            safe_asset_path(&"/rooms/ABCD".parse().unwrap(), "index.html").as_deref(),
            Some("rooms/ABCD")
        );
        assert_eq!(
            safe_asset_path(&"/rooms/ABCD/".parse().unwrap(), "index.html").as_deref(),
            Some("rooms/ABCD")
        );
    }

    #[test]
    fn html_with_zero_quality_does_not_trigger_fallback() {
        let mut headers = HeaderMap::new();
        headers.insert(
            header::ACCEPT,
            HeaderValue::from_static("text/html;q=0, application/json"),
        );
        assert!(!accepts_html(&headers));
    }

    #[test]
    fn repeated_accept_fields_are_combined() {
        let mut headers = HeaderMap::new();
        headers.append(header::ACCEPT, HeaderValue::from_static("application/json"));
        headers.append(header::ACCEPT, HeaderValue::from_static("text/html"));

        assert!(accepts_html(&headers));
    }

    #[test]
    fn webmanifest_uses_registered_manifest_media_type() {
        assert_eq!(
            content_type("site.webmanifest").to_str().unwrap(),
            "application/manifest+json"
        );
    }
}
